# Generated by Django 5.2.8 on 2026-04-22 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TICKET_CREATED', 'Ticket créé'), ('TICKET_ASSIGNED', 'Ticket assigné'), ('TICKET_RESOLVED', 'Ticket résolu'), ('TICKET_ESCALATED', 'Ticket escaladé'), ('TICKET_UPDATED', 'Ticket mis à jour')], max_length=30, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('channel', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('IN_APP', 'In-App')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.UUIDField(db_index=True)),
                ('recipient_type', models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent')], max_length=10)),
                ('recipient_email', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TICKET_CREATED', 'Ticket créé'), ('TICKET_ASSIGNED', 'Ticket assigné'), ('TICKET_RESOLVED', 'Ticket résolu'), ('TICKET_ESCALATED', 'Ticket escaladé'), ('TICKET_UPDATED', 'Ticket mis à jour')], max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('IN_APP', 'In-App')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyée'), ('FAILED', 'Échouée'), ('READ', 'Lue')], db_index=True, default='PENDING', max_length=10)),
                ('ticket_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_id', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['status', 'type'], name='notificatio_status_28abf1_idx')],
            },
        ),
    ]
