# Generated by Django 4.2.16 on 2026-04-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
    ]
