server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: agent-service
          uri: lb://AGENT-SERVICE
          predicates:
            - Path=/agent/**

        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/ticket/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**