server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: agent-service
          uri: lb://AGENT-SERVICE
          predicates:
            - Path=/api/v1/agent/**

        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/v1/ticket/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**