server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: agent-service
          uri: lb:http://AGENT-SERVICE
          predicates:
            - Path=/api/v1/agent/**
        - id: ticket-service
          uri: lb:http://TICKET-SERVICE
          predicates:
            - Path=/api/v1/ticket/**
        - id: notification-service
          uri: lb:http://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**