# Configuration de l'application Notification Service
notification-service.port=8003
notification-service.base-url=http://localhost:8003
spring.application.name=notification-service
# Informations pour l'enregistrement Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
spring.cloud.discovery.enabled=true
# Secrets Django et Base de données
django.secret_key=django-insecure-remote-secret-key-from-config-server
db.password=my-secure-db-password

# Configuration Email (Spring Standard)
spring.mail.username=boutheinabelg1@gmail.com
spring.mail.password=cfnf myax xiub iykm
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
