# ticket-service (Spring Boot)
ticket-service.params.x=11
ticket-service.params.y=22
ticket-service.port=8081
ticket-service.base-url=http://localhost:${ticket-service.port}
ticket-service.api-base-path=/api/v1/tickets
ticket-service.api-url=${ticket-service.base-url}${ticket-service.api-base-path}

# notification-service (Django REST)
notification-service.params.x=11
notification-service.params.y=22
notification-service.port=8000
notification-service.base-url=http://localhost:${notification-service.port}
notification-service.api-base-path=/api/v1
notification-service.api-url=${notification-service.base-url}${notification-service.api-base-path}
notification-service.notifications-path=${notification-service.api-base-path}/notifications
notification-service.templates-path=${notification-service.api-base-path}/templates
