# ticket-service
ticket-service.params.x=66
ticket-service.params.y=29
ticket-service.port=8081
ticket-service.base-url=http://localhost:${ticket-service.port}

# notification-service
notification-service.params.x=66
notification-service.params.y=29
notification-service.port=8000
notification-service.base-url=http://localhost:${notification-service.port}
