# ticket-service
ticket-service.params.x=2277
ticket-service.params.y=5522
ticket-service.port=8081
ticket-service.base-url=http://ticket-service:${ticket-service.port}

# notification-service
notification-service.params.x=2277
notification-service.params.y=5522
notification-service.port=8000
notification-service.base-url=http://notification-service:${notification-service.port}
