# Server
server.port=8081

# Application Name
spring.application.name=ticket-service
spring.cloud.gateway.discovery.locator.enabled=true
# Logging Levels
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=TRACE
logging.level.web=TRACE

# MVC & Request Mapping
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_db?useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create

# Hibernate Properties
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false
