server:
  port: 8761    # port standard de Eureka

spring:
  application:
    name: eureka-server

eureka:
  client:
    # Eureka ne s'enregistre pas lui-même
    register-with-eureka: false
    fetch-registry: false
  server:
    # Délai de démarrage réduit pour les tests
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: health, info